dataset: ruler
data_dir: 4096
model: /ssd1/models/llama-3.1-8b
device: cuda:3
press_name: lu_ea
compression_ratio: 0.8
key_channel_compression_ratio: null
budget_curve_path: curve_data/llama-3.1-8b/ea_0.02_sink4_win1_llama_avg_ratio.npy
fraction: 1.0
max_new_tokens: null
max_context_length: null
compress_questions: false
output_dir: ./0.8_results
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  torch_dtype: auto
press_init_command: LUPress(press=ExpectedAttentionPress(compression_ratio=0.8, n_future_positions=512,
  n_sink=4, use_covariance=True, use_vnorm=True, epsilon=0.02), budget_curve_path='curve_data/llama-3.1-8b/ea_0.02_sink4_win1_llama_avg_ratio.npy',
  sink=4, window=1)
seed: 42
